### ISSUE TITLE
trouble with webpack packaging up prompts

### ISSUE THREAD

**Issue by chancesmith** [terkelg/prompts#111]
I've taken the example on the prompts readme and tried to compile.

After running `npx webpack` I'm getting: `Module not found: Error: Can't resolve 'readline' in '/path/to/test-prompts/node_modules/prompts/dist/elements`

Screenshot of src and console output:
![](https://sh-drop.s3.us-east-1.amazonaws.com/cs/prompts-compile.png)

I see the prompts folder in `node_modules/`. Why is readline not accessible?

**Comment by lukeed** [comment]
Webpack must be configured incorrectly, or not at all. Since `npx` installs & runs in one go, and I see no `webpack.config.js` in your screenshot above, my hunch is that wbepack is borking cuz it's not setup to run/expect native Node modules (like [`readline`](https://nodejs.org/api/readline.html)) out of the gate.

I'd suggest looking at [webpack targets](https://webpack.js.org/configuration/target/) & setting up a config file.

**Comment by chancesmith** [comment]
You nailed it. I wasn't targeting a node environment.

I was hoping for a zero config. 🤷‍♂️ Thank you!

**Comment by lukeed** [comment]
No problem. You can get away with zero-ish config in webpack, but for browser targets. 

You don't _need_ to use a bundler with `prompts` tho – that's more of a design decision than a usage question.

**Comment by terkelg** [comment]
Thanks, @lukeed. Appreciate it
