### ISSUE TITLE
autocomplete use arrow key to navigate between pages

### ISSUE THREAD

**Issue by vivaxy** [terkelg/prompts#163]
Users might not know how to go to next page.

I have been using [inquirer](https://github.com/SBoudrias/Inquirer.js). It has a nicer way of list selection.

![Kapture 2019-06-17 at 11 49 30](https://user-images.githubusercontent.com/4216856/59577513-a2d91100-90f6-11e9-8767-b24a1ff3636f.gif)

**Comment by lumio** [comment]
This could be a great additional option.

**Comment by terkelg** [comment]
I like this too! Good idea

**Comment by bbernstein** [comment]
My pull is a quick change that makes something work, but feel free to use it as an example rather than the verbatim code as it may not follow the vibe of your codebase very well. This would probably be something that can integrate to all selects and multi-selects as well, but I just got it working on `autocomplete`.

**Comment by vivaxy** [comment]
Resolved by https://github.com/terkelg/prompts/pull/230
