### ISSUE TITLE
Multiselect repeated in terminal

### ISSUE THREAD

**Issue by wilmouths** [terkelg/prompts#175]
### Describe the bug
Multiselect repeated in terminal

### To Reproduce
Use Konsole (Kubuntu)
### System

- OS: Kubuntu 19.04
- Terminal: Konsole
- Node version: 10.16.0

### Additional context
![image](https://user-images.githubusercontent.com/38247370/60101308-d30a5a80-975b-11e9-9e63-713bbdbabd06.png)

**Comment by terkelg** [comment]
I think @DrunkenPoney is working on pretty big PR that's going to fix this and other rendering issues

**Comment by DrunkenPoney** [comment]
It might be related to the [same issue](#153) but I'm not sure since this one seems to happen only in [Konsole](https://konsole.kde.org/).
So I'm wondering if it's Konsole which doesn't support the ANSI sequences we use.

**Comment by DrunkenPoney** [comment]
Nevermind I tested almost every ANSI sequences of sisteransi with Konsole using a script I made and they all works fine. So the problem doesn't come from Konsole unless there's a configuration with Konsole that would change how it renders ANSI

**Comment by gajus** [comment]
<img width="415" alt="Screenshot 2019-11-23 at 14 09 46" src="https://user-images.githubusercontent.com/973543/69479925-ec8efb80-0dfa-11ea-978d-74c13274468a.png">

I have the same issue using iTerm2/ fish.

**Comment by gajus** [comment]
It completely crashes if used in combination with roarr.

https://github.com/gajus/roarr

<img width="1920" alt="Screenshot 2019-11-23 at 14 12 05" src="https://user-images.githubusercontent.com/973543/69479964-45f72a80-0dfb-11ea-89d1-e215a1831464.png">

**Comment by DrunkenPoney** [comment]
@gajus I'm pretty sure your problem is not related to this one. Your problem seams to be related to JSON and I don't see how ANSI sequences could break JSON. I would need more information to be sure but your error is most likely a roarr issue.

@terkelg Is it just me or the escape sequences don't make sense? (See screenshot)

![screenshot](https://i.imgur.com/cCdkZ29.png)

<details>
<summary>Legend</summary>

- The green lines seperate the select/multiselect questions with the other ones.
- I've highlighted the text in yellow to make it easier to distinguish.

</details>

The only sequences in the select and multiselect questions are `\e[?25h` (shows the cursor), `\e[?25l` (hides the cursor), `\e[2K` (erase entire line), `\e[1G` (move cursor to beginning of the line) and [SGR](https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_parameters) sequences.

I'm thinking maybe the sequences were not printed because I redirect the output into a file but I don't see why only a couple of them would print and not all of them.
