### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by ui3o** [terkelg/prompts#278]
### New Release Plan

I have seen there autocomplete features on the master, but I would like that from the npm repository.

When do you plan to make a new release?

**Comment by ui3o** [comment]
If that possible than please make a new release with this PR: https://github.com/terkelg/prompts/pull/280
**Let me know when it is possible!**

**Comment by terkelg** [comment]
Yes I will make a new release today

**Comment by futagoza** [comment]
@terkelg  What's in 2.4? I just saw it while checking if any of the dependencies need updating in my personal bundle and publishing package but since there's no changelog and no new release tagged as 2.4 I've got no clue what the changes are apart from the above mentioned.

One might argue "You can simply check the commit history", but I would say a changelog (or even a tagged GitHub release with changes noted) is easier to digest since there's no need to wonder if a commit has added a feature you might need or changed one that you use (which in my case is just optionally promoting for options during bundling/compiling and then asking for a new version for the bundled package, so if those changes mentioned above are the only changes in 2.4 then it means I've got nothing to do to).

**Comment by terkelg** [comment]
I forgot to hit publish on thee release notes.
<img width="446" alt="CleanShot 2020-11-08 at 22 05 45@2x" src="https://user-images.githubusercontent.com/2302254/98484353-1b220400-220f-11eb-8b17-43208bb03fef.png">
