### ISSUE TITLE
What's the difference of prompts and inquirer?

### ISSUE THREAD

**Issue by dushao103500** [terkelg/prompts#29]

**Comment by olstenlarck** [comment]
Smaller. Faster. Easier code base. Not much features. Opinionated.

Probably :dagger:

**Comment by terkelg** [comment]
Prompts is opinionated with main focus on simplicity. Complexity is something we as developers should fight every day. 
To be honest I don't know that much about inquirer. I tried to read some of it's code for inspiration but I gave up.

- **Smaller package**: prompts' codebase is way smaller.
- **2 dependencies (only 1 external)**: Prompts only have 2 dependencies. Both small and both without any dependencies themself. Compare the dependencie graph for [prompts](http://npm.anvaka.com/#/view/2d/prompts) with [inquirer](http://npm.anvaka.com/#/view/2d/inquirer)
- **Testable**: prompts provide a way for you as a developer to programmatically inject responses so you can write test your code.
- **No legacy code**: The code is simple and easy to read. This makes it less error prone, easier to maintain and easier for people to contribute to the project. Prompts uses new JavaScript features like `async/await` which makes the code super tidy - with the downside of only supporting newer version of node.
- **Unified experience**: All prompts inherit the same base class which makes sure the experience is consistent. All prompts respect best practice when it comes to CLI tools (shortcuts etc.) and behave as you'll expect as a CLI-Ninja. 
- **Better documentation**: I think the documentation easier to follow and better structured (with nice gifs, yay!)

**inquirer**
<img width="1096" alt="screen shot 2018-02-28 at 21 40 36" src="https://user-images.githubusercontent.com/2302254/36829663-229101d8-1cd5-11e8-9b24-7134d0aa2312.png">

**prompts**
<img width="575" alt="screen shot 2018-02-28 at 21 40 00" src="https://user-images.githubusercontent.com/2302254/36829664-22ab504c-1cd5-11e8-922a-169e1aa05e16.png">

**Comment by olstenlarck** [comment]
[One more reason about "Why not Inquirer"](https://github.com/enquirer/enquirer/tree/1f9e71157a2358e5e7fcf7ebfc47bfd811bf9894#why-another-prompt-module).
– by Jon Schlinkert (@jonschlinkert), phenomenal community contributor

Above statement is a bit old, probably, because is removed in the latest readme. In anyway, Inquirer is big, it worths to develop on newer nodejs versions and you should always try to bring some idea to minimum.

This leads me through the years and I have tons of small modules similar to some of  more popular lans and they are totally functional and competitive.
